# Generated by Django 5.1.3 on 2024-12-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='brand',
        ),
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
