# Generated by Django 5.1.3 on 2024-12-17 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0004_remove_post_price_remove_post_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
